name: Build

on:
  push:
  repository_dispatch:

jobs:
  build:
    name: Compile
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Compile
      run: make build
  test:
    name: FTest
    runs-on: ${{ matrix.os  }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make ftest
  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install Shellcheck
      run: sudo apt-get install shellcheck
    - name: Vet
      run: make vet
